* Emacs Coment Translate 0.5.0
** Introduction
A small plug-in for Emacs to translate selected text. Because the original idea was to translate code comments into English, it was called Emacs Comment Translate.

** Update information
If you do not set the value of target-language (default is nil), then the program will automatically select target-language according to the language of the selected text.

** How to use?
target-source-language can set the target language, which will correspond to the parameter of translate-shell (:language), the default is :en, after selecting the block, call translate-select-string to translate and replace the selected.

+ Use require:
#+begin_src emacs-lisp
(load "~/.emacs.d/site-lisp/emacs-comment-translate/comment-translate.el")

(setq-default translate-shell-path "/usr/bin/trans"
              target-language "en"
              source-language "zh"
              comment-translate-selected-color "red")

(global-set-key (kbd "C-S-t") 'translate-select-string)
#+end_src

** Depends
This plug-in relies on translate-shell, which can be downloaded in the package repositories of most Linux distributions:

*** Arch
#+begin_src
sudo pacman -S translate-shell
#+end_src

*** Debain
#+begin_src
sudo apt install translate-shell
#+end_src

** Document

You can configure the default conversion list by setting the variable default-translate-languages, it looks like this:
#+begin_src emacs-lisp
(defvar default-translate-languages '(("zh" "en")
                                      ("en" "zh"))
  "Translate source-language to target-language list by default.")
#+end_src

** TODO
*** ✔ Highlight translated paragraphs
CLOSED: [2021-09-17 五 17:41]

*** ⚑ Asynchronous translation

*** ✔ Automatically guess source-language and target-language
CLOSED: [2021-09-18 六 22:58]

*** ⚑ Multiple backend support

*** ⚑ Automatically detect and translate comments in source files
